### ISSUE TITLE
4.0.0 has broken `mixin()` inheritance

### ISSUE THREAD

**Issue by alecgibson** [facing-dev/vue-facing-decorator#164]
I finally got around to trying to bump to v4 again, but mixins are still being problematic for us:

```ts
// msg-mixin.ts

import { Component, Vue } from 'vue-facing-decorator';

@Component({})
export default class MsgMixin extends Vue {
  protected message: string = 'foo';

  public mounted(): void {
    console.log('mounted mixin', this.message);
  }
}
```

```ts
// HelloWorld.vue

<script lang="ts">
import { Component, mixins } from 'vue-facing-decorator';
import MsgMixin from '../mixins/msg-mixin';

@Component({})
export default class HelloWorld extends mixins(MsgMixin) {
  protected override message: string = 'bar';

  public mounted(): void {
    console.log('mounted component', this.message);
  }
}
</script>
```

This compiles fine in `v3.0.4` but typechecks fail in both `v4.0.0` and `v4.0.1` (there's actually *more* failures in `v4.0.1` than `v4.0.0`:

```
src/components/HelloWorld.vue:7:22 - error TS4113: This member cannot have an 'override' modifier because it is not declared in the base class '{ $: ComponentInternalInstance; $data: {}; $props: {}; $attrs: Data; $refs: Data; $slots: Readonly<InternalSlots>; ... 8 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (args_0: R, args_1: R, args_2: OnCleanup) => any : (args_0: any, args_1: any, args...'.

7   protected override message: string = 'bar';
                       ~~~~~~~

src/components/HelloWorld.vue:9:10 - error TS2425: Class '{ $: ComponentInternalInstance; $data: {}; $props: {}; $attrs: Data; $refs: Data; $slots: Readonly<InternalSlots>; ... 8 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (args_0: R, args_1: R, args_2: OnCleanup) => any : (args_0: any, args_1: any, args...' defines instance member property 'mounted', but extended class 'HelloWorld' defines it as instance member function.

9   public mounted(): void {
           ~~~~~~~


Found 2 errors in the same file, starting at: src/components/HelloWorld.vue:7
```

## Minimal working example

https://stackblitz.com/edit/vitejs-vite-udnhbcry?file=package.json

Repro:

1. Open [minimal working example](https://stackblitz.com/edit/vitejs-vite-udnhbcry?file=package.json)
2. `npm i --save vue-facing-decorator@3 && npm run typecheck`
3. No errors
4. `npm i --save vue-facing-decorator@4 && npm run typecheck`
5. Errors, when I expect none
